
package br.com.jarves.formularios;

import br.com.jarves.bancodedados.AnimalDAO;
import br.com.jarves.bancodedados.ClienteDAO;
import br.com.jarves.classes.Animal;
import br.com.jarves.classes.Cliente;
import br.com.jarves.classes.TableFormat;
import br.com.jarves.classes.Util;
import br.com.jarves.util.Global;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
//import net.proteanit.sql.DbUtils;

/**
 *
 * @author Humberto
 */
public class JifConAnimal extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifConEnd
     */
    public JifConAnimal() {
        initComponents();
        carregaLista();
        jftCpf.setVisible(false);
        
        //jtbEndereco.setModel(DbUtils.resultSetToTableModel(EnderecoDAO.listarEnderecos()));
    }
   
    public int flag =0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpPesquisar = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlbNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jbtVoltar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpnDados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCliente = new javax.swing.JTable();
        jftCpf = new javax.swing.JFormattedTextField();
        jrbNome = new javax.swing.JRadioButton();
        jrbCpf = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setTitle("Consulta de Clientes");
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jarves/imagens/Img_drdog.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 410, 160, 260);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta de Clientes / Animais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setLayout(null);

        jlbNome.setText("RGA:");
        jPanel2.add(jlbNome);
        jlbNome.setBounds(30, 40, 80, 30);

        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });
        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomeKeyTyped(evt);
            }
        });
        jPanel2.add(jtfNome);
        jtfNome.setBounds(70, 40, 120, 30);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(10, 150, 760, 20);

        jbtVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jarves/icones/voltar.png.jpg"))); // NOI18N
        jbtVoltar.setText("Voltar");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtVoltar);
        jbtVoltar.setBounds(640, 30, 100, 40);

        jpnDados.setLayout(null);

        jtbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbCliente.setToolTipText("Lista de Endereços");
        jtbCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbCliente);

        jpnDados.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 740, 140);

        jTabbedPane1.addTab("Informações", jpnDados);

        jPanel2.add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 170, 760, 190);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Informações");

        try {
            jftCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftCpfActionPerformed(evt);
            }
        });
        jftCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jftCpfKeyReleased(evt);
            }
        });
        jPanel2.add(jftCpf);
        jftCpf.setBounds(70, 40, 120, 30);

        bgpPesquisar.add(jrbNome);
        jrbNome.setSelected(true);
        jrbNome.setText("RGA");
        jrbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNomeActionPerformed(evt);
            }
        });
        jPanel2.add(jrbNome);
        jrbNome.setBounds(40, 110, 93, 23);

        bgpPesquisar.add(jrbCpf);
        jrbCpf.setText("CPF Proprietário");
        jrbCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCpfActionPerformed(evt);
            }
        });
        jPanel2.add(jrbCpf);
        jrbCpf.setBounds(130, 110, 140, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(50, 20, 830, 390);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jarves/imagens/Rodape_Padrao.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 520, 940, 180);

        getAccessibleContext().setAccessibleName("Consulta de Animais");

        setBounds(0, 0, 941, 725);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtVoltarActionPerformed

    private void jtfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyReleased
       
    if(jtfNome.getText().length()>0)
        filtraLista();
    else
        carregaLista();
    }//GEN-LAST:event_jtfNomeKeyReleased

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    private void jrbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNomeActionPerformed
       jftCpf.setVisible(false);
       jtfNome.setVisible(true);
       jtfNome.grabFocus();
       jlbNome.setText("RGA: ");
       carregaLista();
    }//GEN-LAST:event_jrbNomeActionPerformed

    private void jrbCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCpfActionPerformed
        jtfNome.setVisible(false);
        jftCpf.setVisible(true);
        jftCpf.grabFocus();
        jftCpf.setText("");
        jlbNome.setText("CPF: ");
        carregaLista();
    }//GEN-LAST:event_jrbCpfActionPerformed

    private void jftCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftCpfActionPerformed

    private void jftCpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftCpfKeyReleased
        if(jftCpf.getText().trim().length() == 14){
            filtraLista();
            
        }else{
            carregaLista();
        }
    }//GEN-LAST:event_jftCpfKeyReleased

    private void jtbClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbClienteMouseClicked
        if(evt.getClickCount()>1){
            if (flag ==1){
                int indiceLinha = jtbCliente.getSelectedRow();
                Object cliente = jtbCliente.getValueAt(indiceLinha, 0);
                Object cpf = jtbCliente.getValueAt(indiceLinha, 1);
                Global.jtfCliente.setText(cliente.toString());
                Global.cpf.setText("CPF: "+cpf.toString());
                jifCadAnimal.cpf = cpf.toString();
                Global.jtfCliente.grabFocus();
                flag =0;
                this.dispose();
            }
        }
    }//GEN-LAST:event_jtbClienteMouseClicked

    private void jtfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jtfNomeKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JFormattedTextField jftCpf;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JPanel jpnDados;
    private javax.swing.JRadioButton jrbCpf;
    private javax.swing.JRadioButton jrbNome;
    private javax.swing.JTable jtbCliente;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables

    /**
     * Método para alinhar o internal frame no meio da tela
     */
    public void setPosicao() {  
        Dimension d = this.getDesktopPane().getSize();  
        this.setLocation((d.width - this.getSize().width) / 2, 0);
    }
    
    
    /**
     * Método que filtra a lista de clientes
     */
    public void filtraLista(){
        
        Util u = new Util();
        Animal animal = new Animal();
        Cliente cliente = new Cliente();
        
        String cpf ="";
        String id = "";
        if(jftCpf.getText().trim().length()>13){
           cpf = u.formataCpf(jftCpf.getText());
        }
        if(jtfNome.getText().trim().length()>0){
            id = jtfNome.getText().trim()+"%";
        }
        String titulopessoais[] = {"RGA","Nome","Peso","Raça","Dt Nasc","Sexo","Proprietário"};
              
        Object dados [][]={};
             
        DefaultTableModel modelo = new DefaultTableModel(dados,titulopessoais);
      
        jtbCliente.setDefaultRenderer(Object.class,new TableFormat());
        jtbCliente.setModel(modelo);
        
        
        
        ArrayList<Animal> lista = new AnimalDAO().filtrarAnimal(cpf,id);
            
        for(int i = 0;i<lista.size();i++){
            modelo.addRow(new Object[]{lista.get(i).getIdAnimal(),lista.get(i).getNome(),lista.get(i).getPeso(),lista.get(i).getRaca().getRaca(),
                u.reformataData(lista.get(i).getDtNasc()),lista.get(i).getSexo(),lista.get(i).getCliente().getNomeCliente()
            });
        }
        
    }
    
    public void carregaLista(){
        Util u = new Util();
        String titulopessoais[] = {"RGA","Nome","Peso","Raça","Dt Nasc","Sexo","Proprietário"};
       
        
        Object dados [][]={};
             
        DefaultTableModel modelo = new DefaultTableModel(dados,titulopessoais){
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
            
        jtbCliente.setDefaultRenderer(Object.class,new TableFormat());
        jtbCliente.setModel(modelo);
        
        
         
        ArrayList<Animal> lista = new AnimalDAO().listarAnimal();
               
        for(int i = 0;i<lista.size();i++){
            modelo.addRow(new Object[]{lista.get(i).getIdAnimal(),lista.get(i).getNome(),lista.get(i).getPeso(),lista.get(i).getRaca().getRaca(),
                u.reformataData(lista.get(i).getDtNasc()),lista.get(i).getSexo(),lista.get(i).getCliente().getNomeCliente()
            });
        }
        
    }
    
    
}

