/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jarves.formularios;

import br.com.jarves.bancodedados.ClienteDAO;
import br.com.jarves.bancodedados.ProdutoDAO;
import br.com.jarves.bancodedados.ServicoDAO;
import br.com.jarves.classes.Cliente;
import br.com.jarves.classes.Produtos;
import br.com.jarves.classes.Servico;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.math.BigDecimal;
import java.text.NumberFormat;


/**
 *
 * @author Humberto
 */
public class jifCaixa extends javax.swing.JInternalFrame {

    public BigDecimal quantidadeProduto = new BigDecimal("1");
    public int idCliente;
    public Float dinheiro =0f;
    public Float debito = 0f;
    public Float credito = 0f;
    
    public jifCaixa() {
        initComponents();
        jlbf1.setVisible(false);
        jlbf2.setVisible(false);
        jlbf3.setVisible(false);
        jtfCodigoServico.setVisible(false);
        jtfTroco.setVisible(false);
        jlbFalta.setVisible(false);
        jmnFormaPagto.setVisible(false);
        jlbVlPg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        jtfCodigoProduto = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfValorPagar = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jlbf7 = new javax.swing.JLabel();
        jlbf6 = new javax.swing.JLabel();
        jlbf4 = new javax.swing.JLabel();
        jlbf1 = new javax.swing.JLabel();
        jlbf8 = new javax.swing.JLabel();
        jcbImprimirPDF = new javax.swing.JCheckBox();
        jlbFaltaTroco = new javax.swing.JLabel();
        jlbf3 = new javax.swing.JLabel();
        jlbf2 = new javax.swing.JLabel();
        jlbf5 = new javax.swing.JLabel();
        jtfTroco = new javax.swing.JFormattedTextField();
        jlbFalta = new javax.swing.JLabel();
        jlbTroco = new javax.swing.JLabel();
        jlbf10 = new javax.swing.JLabel();
        jlbVlPg = new javax.swing.JLabel();
        jlbCliente = new javax.swing.JLabel();
        jtfCodigoServico = new javax.swing.JFormattedTextField();
        jtfStatusCaixa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jlbCli = new javax.swing.JLabel();
        jlbCodigo = new javax.swing.JLabel();
        jmnPrincipal = new javax.swing.JMenuBar();
        Comandos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jmnFormaPagto = new javax.swing.JMenu();
        jmiDinheiro = new javax.swing.JMenuItem();
        jmiCredito = new javax.swing.JMenuItem();
        jmiDebito = new javax.swing.JMenuItem();
        jmiSalvar = new javax.swing.JMenuItem();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setTitle("Caixa");
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Caixa"));
        jPanel2.setLayout(null);

        tbProdutos.setAutoCreateRowSorter(true);
        tbProdutos.setBackground(new java.awt.Color(255, 255, 204));
        tbProdutos.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Quant.", "Valor Unit.", "Valor Tot."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProdutos.setRowSelectionAllowed(false);
        tbProdutos.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tbProdutos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbProdutos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbProdutos);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 520, 360);

        jtfCodigoProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtfCodigoProduto.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jtfCodigoProduto.setMaximumSize(new java.awt.Dimension(6, 50));
        jtfCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoProdutoActionPerformed(evt);
            }
        });
        jtfCodigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoProdutoKeyPressed(evt);
            }
        });
        jPanel2.add(jtfCodigoProduto);
        jtfCodigoProduto.setBounds(10, 420, 520, 50);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Valor Total");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(71, 71, 71))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(0, 0, 260, 30);

        jtfValorPagar.setEditable(false);
        jtfValorPagar.setBackground(new java.awt.Color(255, 255, 255));
        jtfValorPagar.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jtfValorPagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jtfValorPagar);
        jtfValorPagar.setBounds(0, 30, 250, 43);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Comandos");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel5.add(jPanel8);
        jPanel8.setBounds(0, 70, 260, 22);

        jlbf7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbf7.setText("F7 - Cancelar Item");
        jPanel5.add(jlbf7);
        jlbf7.setBounds(10, 190, 147, 22);

        jlbf6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbf6.setText("F6 - Alterar quantidade");
        jPanel5.add(jlbf6);
        jlbf6.setBounds(10, 160, 182, 22);

        jlbf4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbf4.setText("F4 - Finalizar venda");
        jPanel5.add(jlbf4);
        jlbf4.setBounds(10, 100, 190, 22);

        jlbf1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbf1.setText("F1 - Dinheiro");
        jPanel5.add(jlbf1);
        jlbf1.setBounds(10, 100, 103, 22);

        jlbf8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbf8.setText("F8 - Identificar Serviço");
        jPanel5.add(jlbf8);
        jlbf8.setBounds(10, 220, 200, 22);

        jcbImprimirPDF.setSelected(true);
        jcbImprimirPDF.setText("Gerar PDF da venda para imprimir");
        jPanel5.add(jcbImprimirPDF);
        jcbImprimirPDF.setBounds(309, 188, 187, 23);

        jlbFaltaTroco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel5.add(jlbFaltaTroco);
        jlbFaltaTroco.setBounds(10, 320, 80, 50);

        jlbf3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbf3.setText("F3 - Cartão de Débito");
        jPanel5.add(jlbf3);
        jlbf3.setBounds(10, 160, 171, 22);

        jlbf2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbf2.setText("F2 - Cartão de Crédito");
        jPanel5.add(jlbf2);
        jlbf2.setBounds(10, 130, 210, 22);

        jlbf5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbf5.setText("F5 - Identificar Cliente");
        jPanel5.add(jlbf5);
        jlbf5.setBounds(10, 130, 176, 22);

        jtfTroco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtfTroco.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jtfTroco.setMaximumSize(new java.awt.Dimension(6, 50));
        jtfTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTrocoActionPerformed(evt);
            }
        });
        jtfTroco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfTrocoKeyPressed(evt);
            }
        });
        jPanel5.add(jtfTroco);
        jtfTroco.setBounds(100, 250, 130, 50);

        jlbFalta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel5.add(jlbFalta);
        jlbFalta.setBounds(130, 320, 80, 50);

        jlbTroco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel5.add(jlbTroco);
        jlbTroco.setBounds(130, 320, 80, 50);

        jlbf10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbf10.setText("F9 - Sair");
        jPanel5.add(jlbf10);
        jlbf10.setBounds(10, 250, 67, 22);

        jlbVlPg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbVlPg.setText("Valor:");
        jPanel5.add(jlbVlPg);
        jlbVlPg.setBounds(20, 270, 46, 22);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(550, 90, 250, 460);

        jlbCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jlbCliente);
        jlbCliente.setBounds(10, 480, 520, 40);

        jtfCodigoServico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtfCodigoServico.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jtfCodigoServico.setMaximumSize(new java.awt.Dimension(6, 50));
        jtfCodigoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoServicoActionPerformed(evt);
            }
        });
        jtfCodigoServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoServicoKeyPressed(evt);
            }
        });
        jPanel2.add(jtfCodigoServico);
        jtfCodigoServico.setBounds(10, 420, 520, 50);

        jtfStatusCaixa.setEditable(false);
        jtfStatusCaixa.setBackground(new java.awt.Color(255, 255, 255));
        jtfStatusCaixa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfStatusCaixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfStatusCaixa.setText("Caixa aberto");
        jPanel2.add(jtfStatusCaixa);
        jtfStatusCaixa.setBounds(550, 40, 260, 35);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Status do caixa");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(610, 10, 137, 22);

        jlbCli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jlbCli);
        jlbCli.setBounds(10, 520, 520, 40);

        jlbCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbCodigo.setText("Código do Produto:");
        jPanel2.add(jlbCodigo);
        jlbCodigo.setBounds(10, 390, 210, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 0, 820, 570);

        Comandos.setText("Comandos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem1.setText("Quantidade");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Comandos.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Comandos.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem3.setText("Cancelar Produto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Comandos.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem4.setText("Identificar Cliente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Comandos.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem5.setText("Finalizar Venda");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Comandos.add(jMenuItem5);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItem9.setText("Identificar Serviço");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        Comandos.add(jMenuItem9);

        jmnPrincipal.add(Comandos);

        jmnFormaPagto.setText("Formas de Pagamento");

        jmiDinheiro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jmiDinheiro.setText("Dinheiro");
        jmiDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDinheiroActionPerformed(evt);
            }
        });
        jmnFormaPagto.add(jmiDinheiro);

        jmiCredito.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jmiCredito.setText("Credito");
        jmiCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCreditoActionPerformed(evt);
            }
        });
        jmnFormaPagto.add(jmiCredito);

        jmiDebito.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jmiDebito.setText("Debito");
        jmiDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDebitoActionPerformed(evt);
            }
        });
        jmnFormaPagto.add(jmiDebito);

        jmiSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jmiSalvar.setText("Salva Venda");
        jmiSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalvarActionPerformed(evt);
            }
        });
        jmnFormaPagto.add(jmiSalvar);

        jmnPrincipal.add(jmnFormaPagto);

        setJMenuBar(jmnPrincipal);

        setBounds(0, 0, 860, 673);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jtfCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoProdutoActionPerformed
        // TODO add your handling code here:
        statusCaixa();
    }//GEN-LAST:event_jtfCodigoProdutoActionPerformed

    private void jtfCodigoProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoProdutoKeyPressed
       
        keyPressed(evt);
        this.jtfValorPagar.setText(NumberFormat.getCurrencyInstance().format(somaEAtualizaValorTotal()));
        statusCaixa();
    }//GEN-LAST:event_jtfCodigoProdutoKeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int linha = tbProdutos.getSelectedRow();
        String nome = (String) tbProdutos.getValueAt(linha,1);
        String item = (String) tbProdutos.getValueAt(linha, 0);

        int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja"
                + " excluir o item: " + item +  "\n " + nome + " ?", "Atenção", JOptionPane.YES_NO_OPTION);
        //se sim exclui, se não não faz nada    
        if (opcao == JOptionPane.OK_OPTION) {

            DefaultTableModel modelo = (DefaultTableModel) tbProdutos.getModel();
            int linhaSelecionada = tbProdutos.getSelectedRow();
            System.out.print("Você selecionou a linha" + linhaSelecionada);
            // Verificamos se existe realmente alguma linha selecionada
            if (linhaSelecionada < 0) {
                return;
            } else {
                // Remove a linha
                modelo.removeRow(linhaSelecionada);
                
                this.jtfValorPagar.setText(NumberFormat.getCurrencyInstance().format(somaEAtualizaValorTotal()));
                statusCaixa();
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       quantidadeProduto = BigDecimal.valueOf(Double.parseDouble(JOptionPane.showInputDialog("Informe a Quantidade")));
       
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ClienteDAO clid = new ClienteDAO();
        Cliente cliente = new Cliente();
        
        String cpf = JOptionPane.showInputDialog("Informe CPF");
        if(cpf!= null){
            cliente.setCpf(cpf);
            clid.getCliente(cliente);
            if(cliente.getNomeCliente()!=null){
                idCliente = cliente.getIdCliente();
                jlbCli.setText("Cliente Identificado: "+cliente.getNomeCliente());
                jtfCodigoProduto.grabFocus();
            }else{
                JOptionPane.showMessageDialog(null, "Cliente Não Localizado");
            }
        }
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jtfCodigoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoServicoActionPerformed

    private void jtfCodigoServicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoServicoKeyPressed
       
        
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            
            Produtos modelProdutos = new Produtos();
            ProdutoDAO pd = new ProdutoDAO();
            
            ServicoDAO sdao = new ServicoDAO();
            Servico servico = new Servico();
                    
            DefaultTableModel modelo = (DefaultTableModel) tbProdutos.getModel();
            
            tbProdutos.setModel(modelo);
            
            try {
                servico = sdao.getServico(Integer.parseInt(this.jtfCodigoServico.getText()));
                modelProdutos = pd.getProdutosCodigo(this.jtfCodigoProduto.getText());
                
                BigDecimal valorArredondado = (servico.getPrecoServico().multiply(quantidadeProduto));
                
                
                
                modelo.addRow(new Object[]{
                    
                    servico.getIdServico(),
                    servico.getNomeServico(),
                    quantidadeProduto,
                    NumberFormat.getCurrencyInstance().format(servico.getPrecoServico()).replace("R$ ", ""),
                    NumberFormat.getCurrencyInstance().format(valorArredondado).replace("R$ ", "").replace(",", ".")
                });
                jlbCliente.setText("Cliente: "+servico.getAnimal().getNome() + " Proprietário: "+servico.getCliente().getNomeCliente());
                idCliente = servico.getCliente().getIdCliente();
                quantidadeProduto = BigDecimal.valueOf(1);
                this.jtfCodigoServico.setText(null);
                this.jtfValorPagar.setText(NumberFormat.getCurrencyInstance().format(somaEAtualizaValorTotal()).replace(",", "."));
                jlbFalta.setText(jtfValorPagar.getText().replace("R$ ", ""));
            } catch (Exception ex) {
                jtfCodigoServico.setText("");
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Serviço inexistente!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
        statusCaixa();
    }//GEN-LAST:event_jtfCodigoServicoKeyPressed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        finalizaVenda();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jtfTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTrocoActionPerformed

    private void jtfTrocoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTrocoKeyPressed
      
    }//GEN-LAST:event_jtfTrocoKeyPressed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        jtfCodigoServico.setVisible(true);
        jtfCodigoProduto.setVisible(false);
        jlbCodigo.setText("Código do Serviço:");
        jtfCodigoServico.grabFocus();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jmiDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDinheiroActionPerformed
        dinheiro = dinheiro + Float.parseFloat(jtfTroco.getText());
        calculaTroco(Float.parseFloat(jtfTroco.getText()));
        jlbFalta.setVisible(true);
        jtfTroco.setText(null);
    }//GEN-LAST:event_jmiDinheiroActionPerformed

    private void jmiCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCreditoActionPerformed
        credito = credito + Float.parseFloat(jtfTroco.getText());
        calculaTroco(Float.parseFloat(jtfTroco.getText()));
        jlbFalta.setVisible(true);
        jtfTroco.setText(null);
    }//GEN-LAST:event_jmiCreditoActionPerformed

    private void jmiDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDebitoActionPerformed
        debito = debito + Float.parseFloat(jtfTroco.getText());
        calculaTroco(Float.parseFloat(jtfTroco.getText()));
        jlbFalta.setVisible(true);
        jtfTroco.setText(null);
    }//GEN-LAST:event_jmiDebitoActionPerformed

    private void jmiSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalvarActionPerformed
        
        
        for(int i =0;i< tbProdutos.getRowCount();i++){
            String nome = (String) tbProdutos.getValueAt(i,1);
            String item = (String) tbProdutos.getValueAt(i, 0);
            JOptionPane.showMessageDialog(null,nome+"\n"+item);
        }
        
        
        
    }//GEN-LAST:event_jmiSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Comandos;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox jcbImprimirPDF;
    private javax.swing.JLabel jlbCli;
    private javax.swing.JLabel jlbCliente;
    private javax.swing.JLabel jlbCodigo;
    private javax.swing.JLabel jlbFalta;
    private javax.swing.JLabel jlbFaltaTroco;
    private javax.swing.JLabel jlbTroco;
    private javax.swing.JLabel jlbVlPg;
    private javax.swing.JLabel jlbf1;
    private javax.swing.JLabel jlbf10;
    private javax.swing.JLabel jlbf2;
    private javax.swing.JLabel jlbf3;
    private javax.swing.JLabel jlbf4;
    private javax.swing.JLabel jlbf5;
    private javax.swing.JLabel jlbf6;
    private javax.swing.JLabel jlbf7;
    private javax.swing.JLabel jlbf8;
    private javax.swing.JMenuItem jmiCredito;
    private javax.swing.JMenuItem jmiDebito;
    private javax.swing.JMenuItem jmiDinheiro;
    private javax.swing.JMenuItem jmiSalvar;
    private javax.swing.JMenu jmnFormaPagto;
    private javax.swing.JMenuBar jmnPrincipal;
    private javax.swing.JFormattedTextField jtfCodigoProduto;
    private javax.swing.JFormattedTextField jtfCodigoServico;
    private javax.swing.JTextField jtfStatusCaixa;
    private javax.swing.JFormattedTextField jtfTroco;
    private javax.swing.JTextField jtfValorPagar;
    private javax.swing.JTable tbProdutos;
    // End of variables declaration//GEN-END:variables

    /**
     * Método para alinhar o internal frame no meio da tela
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, 0);
    }
 //PEGA LETRAS DIGITADAS       
    public void keyPressed(java.awt.event.KeyEvent e) {
        if (e.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            
            Produtos modelProdutos = new Produtos();
            ProdutoDAO pd = new ProdutoDAO();
            DefaultTableModel modelo = (DefaultTableModel) tbProdutos.getModel();
            
            tbProdutos.setModel(modelo);
            
            try {
                
                modelProdutos = pd.getProdutosCodigo(this.jtfCodigoProduto.getText());
                
                BigDecimal valorArredondado =  (modelProdutos.getPrecoProduto().getPrecoVenda().multiply(quantidadeProduto)  );
                
                
                modelo.addRow(new Object[]{
                    
                    modelProdutos.getEanProduto(),
                    modelProdutos.getDescricao(),
                    quantidadeProduto,
                    NumberFormat.getCurrencyInstance().format(modelProdutos.getPrecoProduto().getPrecoVenda()).replace("R$ ", ""),
                    NumberFormat.getCurrencyInstance().format(valorArredondado).replace("R$ ", "").replace(",", ".")
                });

                quantidadeProduto = BigDecimal.valueOf(1);
                this.jtfCodigoProduto.setText(null);
            } catch (Exception ex) {
                jtfCodigoProduto.setText("");
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Produto Inexistente!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }
    
     public void statusCaixa() {
        DefaultTableModel modelo = (DefaultTableModel) tbProdutos.getModel();
        if (modelo.getRowCount() < 1) {
            jtfStatusCaixa.setText("Caixa Livre");
        } else {
            jtfStatusCaixa.setText("Venda Aberta");
        }
    }
     
     private void limparTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tbProdutos.getModel();
        modelo.setNumRows(0);
        statusCaixa();
    }
    
    /**
     * Soma e atualiza os valores total
     * @return 
     */
    private float somaEAtualizaValorTotal() {
           
        float soma = 0;
        float valor = 0;
        int cont = tbProdutos.getRowCount();
        for (int i = 0; i < cont; i++) {
            valor = Float.parseFloat(String.valueOf(tbProdutos.getValueAt(i, 4)));
            soma = valor+soma;
        }
        return soma;
    }
    
    public boolean salvaVenda(){
        boolean retorno = false;
        int t = tbProdutos.getRowCount();
        
        JOptionPane.showMessageDialog(null, t);
        
        return retorno;
    
    
    
    }
    
    public void calculaTroco(Float valor){
    
        Float vTotal = Float.parseFloat(jtfValorPagar.getText().replace("R$ ",""));
        Float falta = Float.parseFloat(jlbFalta.getText());
        
        falta = falta - valor;
        jlbFalta.setText(NumberFormat.getCurrencyInstance().format(falta).replace(",", ".").replace("R$ ", ""));
        jlbFaltaTroco.setText("Falta: ");
        jlbFaltaTroco.setForeground(Color.red);
        if(falta < 0){
            Float troco = falta;
            jlbFaltaTroco.setForeground(Color.blue);
            jlbFaltaTroco.setText("Troco: ");
            jlbTroco.setText(NumberFormat.getCurrencyInstance().format(troco).replace("-", "").replace(",", ".").replace("R$ ", "")); 
            jlbFalta.setText(null);
       }
        
        
        
        
    }
    
    public void finalizaVenda(){
        jmnFormaPagto.setVisible(true);
        jtfTroco.setVisible(true);
        jtfCodigoProduto.setEnabled(false);
        jtfCodigoServico.setEnabled(false);
        
        jlbf1.setVisible(true);
        jlbf2.setVisible(true);
        jlbf3.setVisible(true);
        jlbf4.setVisible(false);
        jlbf5.setVisible(false);
        jlbf6.setVisible(false);
        jlbf7.setVisible(false);
        jlbf8.setVisible(false);
        jlbf10.setVisible(false);
        jlbVlPg.setVisible(true);
        jtfTroco.grabFocus();
    }
         
    
}
