/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jarves.formularios;

import br.com.jarves.bancodedados.EnderecoDAO;
import java.awt.Dimension;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Humberto
 */
public class jifConEnd extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifConEnd
     */
    public jifConEnd() {
        initComponents();
        
        jtbEndereco.setModel(DbUtils.resultSetToTableModel(EnderecoDAO.listarEnderecos()));
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbEndereco = new javax.swing.JTable();
        jbtVoltar = new javax.swing.JButton();
        jbtPesquisar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setTitle("Consulta de Endereços");
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Endereços"));
        jPanel2.setLayout(null);

        jLabel1.setText("Endereço:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 80, 80, 20);

        jtfEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfEnderecoKeyReleased(evt);
            }
        });
        jPanel2.add(jtfEndereco);
        jtfEndereco.setBounds(100, 70, 410, 30);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(10, 130, 680, 20);

        jtbEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbEndereco);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 680, 160);

        jbtVoltar.setText("Voltar");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtVoltar);
        jbtVoltar.setBounds(580, 30, 100, 40);

        jbtPesquisar.setText("Pesquisar");
        jbtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtPesquisar);
        jbtPesquisar.setBounds(580, 80, 100, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 700, 340);

        setBounds(0, 0, 711, 386);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtVoltarActionPerformed

    private void jtfEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEnderecoKeyReleased
        if(jtfEndereco.getText().length()>4)
        jtbEndereco.setModel(DbUtils.resultSetToTableModel(EnderecoDAO.pesquisarEnderecos(jtfEndereco.getText().trim().toLowerCase())));
    }//GEN-LAST:event_jtfEnderecoKeyReleased

    private void jbtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisarActionPerformed
         if(jtfEndereco.getText().length()>4)
        jtbEndereco.setModel(DbUtils.resultSetToTableModel(EnderecoDAO.pesquisarEnderecos(jtfEndereco.getText().trim().toLowerCase())));
    }//GEN-LAST:event_jbtPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtPesquisar;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JTable jtbEndereco;
    private javax.swing.JTextField jtfEndereco;
    // End of variables declaration//GEN-END:variables

 public void setPosicao() {  
        Dimension d = this.getDesktopPane().getSize();  
        this.setLocation((d.width - this.getSize().width) / 2, 0);
    }
}

