/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jarves.formularios;

import br.com.jarves.bancodedados.CategoriaDAO;
import br.com.jarves.classes.Categoria;
import br.com.jarves.classes.PrecoProduto;
import br.com.jarves.classes.Produtos;
import br.com.jarves.classes.TableFormat;
import java.awt.Dimension;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Humberto
 */
public final class jifCadProduto extends javax.swing.JInternalFrame {

    
    public jifCadProduto() {
        initComponents();
        carregaCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jtfCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbUnidade = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtGravar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jtfDescricao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfPrecoCom = new javax.swing.JFormattedTextField();
        jtfPrecoVenda = new javax.swing.JFormattedTextField();
        jtfLucro = new javax.swing.JTextField();
        jtfImposto = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setTitle("Registro de Produtos");
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setLayout(null);

        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyPressed(evt);
            }
        });
        jPanel2.add(jtfCodigo);
        jtfCodigo.setBounds(110, 40, 210, 30);

        jLabel1.setText("Cógido:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 40, 70, 30);

        jLabel2.setText("Unidade:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 120, 50, 30);

        jcbUnidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Pacote", "Kilo", "Unidade" }));
        jPanel2.add(jcbUnidade);
        jcbUnidade.setBounds(110, 120, 130, 30);

        jLabel3.setText("Preço Compra:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 210, 80, 30);

        jLabel4.setText("Categoria:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 160, 60, 30);

        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));
        jPanel2.add(jcbCategoria);
        jcbCategoria.setBounds(110, 160, 130, 30);

        jLabel5.setText("Lucro %:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(170, 210, 50, 30);

        jLabel6.setText("Preço Venda:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(390, 210, 80, 30);

        jLabel7.setText("Imposto %:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(270, 210, 80, 30);

        jbtGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jarves/icones/Database.png"))); // NOI18N
        jbtGravar.setText("Gravar");
        jbtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGravarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtGravar);
        jbtGravar.setBounds(50, 290, 100, 30);

        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jarves/icones/Delete.png"))); // NOI18N
        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtCancelar);
        jbtCancelar.setBounds(180, 290, 110, 30);

        jtfDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDescricaoKeyPressed(evt);
            }
        });
        jPanel2.add(jtfDescricao);
        jtfDescricao.setBounds(110, 80, 420, 30);

        jLabel8.setText("Descrição:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 80, 70, 30);

        jtfPrecoCom.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jtfPrecoCom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPrecoComKeyTyped(evt);
            }
        });
        jPanel2.add(jtfPrecoCom);
        jtfPrecoCom.setBounds(100, 210, 60, 30);

        jtfPrecoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jtfPrecoVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPrecoVendaKeyTyped(evt);
            }
        });
        jPanel2.add(jtfPrecoVenda);
        jtfPrecoVenda.setBounds(470, 210, 60, 30);
        jPanel2.add(jtfLucro);
        jtfLucro.setBounds(220, 210, 40, 30);
        jPanel2.add(jtfImposto);
        jtfImposto.setBounds(330, 210, 50, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(130, 40, 670, 350);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jarves/imagens/Img_Compras.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 420, 300, 190);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jarves/imagens/Rodape_Padrao.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 520, 940, 180);

        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 440, 190, 160);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 940, 700);

        setBounds(0, 0, 941, 725);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyPressed
       if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
           System.out.println("Enter");
       }
        
    }//GEN-LAST:event_jtfCodigoKeyPressed

    private void jtfDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescricaoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDescricaoKeyPressed

    private void jbtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGravarActionPerformed
        Produtos produtos = new Produtos();
        Categoria categoria = new Categoria();
        PrecoProduto preprod = new PrecoProduto();
        
        categoria.setNomeCategoria(jcbCategoria.getSelectedItem().toString().toLowerCase());
        BigDecimal precoCom  = new BigDecimal(jtfPrecoCom.getText().replaceAll("\\.","").replace(",", ".").replace("R$ ", ""));
        BigDecimal precoVen  = new BigDecimal(jtfPrecoVenda.getText().replaceAll("\\.","").replace(",", ".").replace("R$ ", ""));
        preprod.setPrecoCompra(precoCom);
    }//GEN-LAST:event_jbtGravarActionPerformed

    private void jtfPrecoComKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecoComKeyTyped
        String caracteres="0987654321.,";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jtfPrecoComKeyTyped

    private void jtfPrecoVendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecoVendaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrecoVendaKeyTyped

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        BigDecimal precoCom  = new BigDecimal(jtfPrecoCom.getText().replaceAll("\\.","").replace(",", ".").replace("R$ ", ""));
        BigDecimal precoVen  = new BigDecimal(jtfPrecoVenda.getText().replaceAll("\\.","").replace(",", ".").replace("R$ ", ""));
        BigDecimal imposto = new BigDecimal(jtfImposto.getText());
        BigDecimal imp = precoCom.multiply(imposto).divide(new BigDecimal(100));
        
        System.out.println(precoCom);
        System.out.println(precoVen);
        System.out.println(imp);
        System.out.println(jtfLucro.getText());
    }//GEN-LAST:event_jbtCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtGravar;
    private javax.swing.JComboBox jcbCategoria;
    private javax.swing.JComboBox jcbUnidade;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfImposto;
    private javax.swing.JTextField jtfLucro;
    private javax.swing.JFormattedTextField jtfPrecoCom;
    private javax.swing.JFormattedTextField jtfPrecoVenda;
    // End of variables declaration//GEN-END:variables

    /**
     * Método para alinhar o internal frame no meio da tela
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, 0);
    }

     public void carregaCategoria() {
         
        ArrayList<Categoria> lista = new CategoriaDAO().listarCategoria();

        for (Categoria lista1 : lista) {

            jcbCategoria.addItem(lista1.getNomeCategoria());
            
        }

    }

    

      
    
}
