/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jarves.formularios;

import br.com.jarves.bancodedados.CategoriaDAO;
import br.com.jarves.bancodedados.ProdutoDAO;
import br.com.jarves.classes.Categoria;
import br.com.jarves.classes.PrecoProduto;
import br.com.jarves.classes.Produtos;

import java.awt.Dimension;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Humberto
 */
public final class jifCadProduto extends javax.swing.JInternalFrame {

    int idProduto;

    public jifCadProduto() {
        initComponents();
        carregaCategoria();
        jbtAlterar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jtfCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbUnidade = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtGravar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jtfDescricao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfPrecoCom = new javax.swing.JFormattedTextField();
        jtfPrecoVenda = new javax.swing.JFormattedTextField();
        jtfLucro = new javax.swing.JTextField();
        jtfImposto = new javax.swing.JTextField();
        jbtAlterar = new javax.swing.JButton();
        jbtSair = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setTitle("Registro de Produtos");
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Produtos"));
        jPanel2.setLayout(null);

        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyPressed(evt);
            }
        });
        jPanel2.add(jtfCodigo);
        jtfCodigo.setBounds(110, 40, 210, 30);

        jLabel1.setText("Cógido:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 40, 70, 30);

        jLabel2.setText("Unidade:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 120, 50, 30);

        jcbUnidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Pacote", "Kilo", "Unidade" }));
        jPanel2.add(jcbUnidade);
        jcbUnidade.setBounds(110, 120, 130, 30);

        jLabel3.setText("Preço Compra:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 210, 80, 30);

        jLabel4.setText("Categoria:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 160, 60, 30);

        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));
        jPanel2.add(jcbCategoria);
        jcbCategoria.setBounds(110, 160, 130, 30);

        jLabel5.setText("Lucro %:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(170, 210, 50, 30);

        jLabel6.setText("Preço Venda:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(390, 210, 80, 30);

        jLabel7.setText("Imposto %:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(270, 210, 80, 30);

        jbtGravar.setText("Gravar");
        jbtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGravarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtGravar);
        jbtGravar.setBounds(30, 290, 90, 30);

        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtCancelar);
        jbtCancelar.setBounds(130, 290, 90, 30);

        jtfDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDescricaoKeyPressed(evt);
            }
        });
        jPanel2.add(jtfDescricao);
        jtfDescricao.setBounds(110, 80, 210, 30);

        jLabel8.setText("Descrição:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 80, 70, 30);

        jtfPrecoCom.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jtfPrecoCom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfPrecoComFocusLost(evt);
            }
        });
        jtfPrecoCom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPrecoComKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPrecoComKeyTyped(evt);
            }
        });
        jPanel2.add(jtfPrecoCom);
        jtfPrecoCom.setBounds(100, 210, 60, 30);

        jtfPrecoVenda.setEditable(false);
        jtfPrecoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jtfPrecoVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPrecoVendaKeyTyped(evt);
            }
        });
        jPanel2.add(jtfPrecoVenda);
        jtfPrecoVenda.setBounds(470, 210, 60, 30);

        jtfLucro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfLucroFocusLost(evt);
            }
        });
        jtfLucro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfLucroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfLucroKeyTyped(evt);
            }
        });
        jPanel2.add(jtfLucro);
        jtfLucro.setBounds(220, 210, 40, 30);

        jtfImposto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfImpostoFocusLost(evt);
            }
        });
        jtfImposto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfImpostoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfImpostoKeyTyped(evt);
            }
        });
        jPanel2.add(jtfImposto);
        jtfImposto.setBounds(330, 210, 50, 30);

        jbtAlterar.setText("Alterar");
        jbtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtAlterar);
        jbtAlterar.setBounds(30, 290, 90, 30);

        jbtSair.setText("Sair");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });
        jPanel2.add(jbtSair);
        jbtSair.setBounds(230, 290, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 0, 610, 350);

        setBounds(0, 0, 632, 404);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            ProdutoDAO pdao = new ProdutoDAO();
            Produtos p = new Produtos();
            p.setEanProduto(jtfCodigo.getText().trim());
            pdao.getProdutos(p);
            System.out.println(p.getDescricao());
            if (!p.getDescricao().equals("")) {
                if (JOptionPane.showConfirmDialog(null, "Produto já Registrado, Deseja Exibir os Dados?", "Pergunta", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    idProduto = p.getIdProduto();
                    jtfDescricao.setText(p.getDescricao());
                    jcbUnidade.setSelectedItem(p.getUnidade());
                    jcbCategoria.setSelectedItem(p.getCategoria().getNomeCategoria());

                    jtfPrecoCom.setText(NumberFormat.getCurrencyInstance().format(p.getPrecoProduto().getPrecoCompra()).replace("R$ ", ""));
                    jtfLucro.setText(NumberFormat.getCurrencyInstance().format(p.getPrecoProduto().getLucro()).replace("R$ ", ""));
                    jtfImposto.setText(NumberFormat.getCurrencyInstance().format(p.getPrecoProduto().getImposto()).replace("R$ ", ""));
                    jtfPrecoVenda.setText(NumberFormat.getCurrencyInstance().format(p.getPrecoProduto().getPrecoVenda()).replace("R$ ", ""));

                    jbtGravar.setVisible(false);
                    jbtAlterar.setVisible(true);
                    jtfCodigo.setEditable(false);
                } else {
                    limparCampos();
                }
            } else {
                jtfDescricao.grabFocus();

            }

        }

    }//GEN-LAST:event_jtfCodigoKeyPressed

    private void jtfDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescricaoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDescricaoKeyPressed

    private void jbtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGravarActionPerformed

        if (validaCampos()) {
            Produtos produtos = new Produtos();
            Categoria categoria = new Categoria();
            PrecoProduto preprod = new PrecoProduto();
            ProdutoDAO pdao = new ProdutoDAO();

            categoria.setNomeCategoria(jcbCategoria.getSelectedItem().toString().toLowerCase());

            BigDecimal precoCom = new BigDecimal(jtfPrecoCom.getText().replaceAll("\\.", "").replace(",", ".").replace("R$ ", ""));
            BigDecimal lucro = new BigDecimal(jtfLucro.getText().replaceAll("\\.", "").replace(",", ".").replace("R$ ", ""));
            BigDecimal imposto = new BigDecimal(jtfImposto.getText().replaceAll("\\.", "").replace(",", ".").replace("R$ ", ""));
            BigDecimal precoVen = new BigDecimal(jtfPrecoVenda.getText().replaceAll("\\.", "").replace(",", ".").replace("R$ ", ""));

            preprod.setPrecoCompra(precoCom);
            preprod.setImposto(imposto);
            preprod.setLucro(lucro);
            preprod.setPrecoVenda(precoVen);

            produtos.setCategoria(categoria);
            produtos.setPrecoProduto(preprod);
            produtos.setEanProduto(jtfCodigo.getText().trim());
            produtos.setDescricao(jtfDescricao.getText().trim().toLowerCase());
            produtos.setUnidade(jcbUnidade.getSelectedItem().toString());

            JOptionPane.showMessageDialog(null, pdao.insereProdutos(produtos));
            limparCampos();
        }
    }//GEN-LAST:event_jbtGravarActionPerformed

    private void jtfPrecoComKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecoComKeyTyped
        String caracteres = "0987654321.,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfPrecoComKeyTyped

    private void jtfPrecoVendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecoVendaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrecoVendaKeyTyped

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        limparCampos();
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jtfPrecoComFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPrecoComFocusLost
        if (jtfPrecoCom.getText().trim().equals("")) {
            calculaPreco();
        }
    }//GEN-LAST:event_jtfPrecoComFocusLost

    private void jtfLucroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfLucroFocusLost
        if (!jtfLucro.getText().trim().equals("")) {
            calculaPreco();
        }
    }//GEN-LAST:event_jtfLucroFocusLost

    private void jtfImpostoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfImpostoFocusLost
        if (!jtfImposto.getText().trim().equals("")) {
            calculaPreco();
        }
    }//GEN-LAST:event_jtfImpostoFocusLost

    private void jtfPrecoComKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecoComKeyReleased
        calculaPreco();
    }//GEN-LAST:event_jtfPrecoComKeyReleased

    private void jtfLucroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfLucroKeyReleased
        calculaPreco();
    }//GEN-LAST:event_jtfLucroKeyReleased

    private void jtfImpostoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfImpostoKeyReleased
        calculaPreco();
    }//GEN-LAST:event_jtfImpostoKeyReleased

    private void jtfLucroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfLucroKeyTyped
        String caracteres = "0987654321,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfLucroKeyTyped

    private void jtfImpostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfImpostoKeyTyped
        String caracteres = "0987654321,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfImpostoKeyTyped

    private void jbtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAlterarActionPerformed

        if (validaCampos()) {
            Produtos produtos = new Produtos();
            Categoria categoria = new Categoria();
            PrecoProduto preprod = new PrecoProduto();
            ProdutoDAO pdao = new ProdutoDAO();

            categoria.setNomeCategoria(jcbCategoria.getSelectedItem().toString().toLowerCase());

            BigDecimal precoCom = new BigDecimal(jtfPrecoCom.getText().replaceAll("\\.", "").replace(",", ".").replace("R$ ", ""));
            BigDecimal lucro = new BigDecimal(jtfLucro.getText().replaceAll("\\.", "").replace(",", ".").replace("R$ ", ""));
            BigDecimal imposto = new BigDecimal(jtfImposto.getText().replaceAll("\\.", "").replace(",", ".").replace("R$ ", ""));
            BigDecimal precoVen = new BigDecimal(jtfPrecoVenda.getText().replaceAll("\\.", "").replace(",", ".").replace("R$ ", ""));

            preprod.setPrecoCompra(precoCom);
            preprod.setImposto(imposto);
            preprod.setLucro(lucro);
            preprod.setPrecoVenda(precoVen);

            produtos.setIdProduto(idProduto);
            produtos.setCategoria(categoria);
            produtos.setPrecoProduto(preprod);
            produtos.setEanProduto(jtfCodigo.getText().trim());
            produtos.setDescricao(jtfDescricao.getText().trim().toLowerCase());
            produtos.setUnidade(jcbUnidade.getSelectedItem().toString());

            JOptionPane.showMessageDialog(null, pdao.alteraProdutos(produtos));
            limparCampos();
        }
    }//GEN-LAST:event_jbtAlterarActionPerformed

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtAlterar;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtGravar;
    private javax.swing.JButton jbtSair;
    private javax.swing.JComboBox jcbCategoria;
    private javax.swing.JComboBox jcbUnidade;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfImposto;
    private javax.swing.JTextField jtfLucro;
    private javax.swing.JFormattedTextField jtfPrecoCom;
    private javax.swing.JFormattedTextField jtfPrecoVenda;
    // End of variables declaration//GEN-END:variables

    /**
     * Método para alinhar o internal frame no meio da tela
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, 0);
    }

    /**
     * Método que carraga lista de categorias de Produtos
     */
    public void carregaCategoria() {

        ArrayList<Categoria> lista = new CategoriaDAO().listarCategoria();

        for (Categoria lista1 : lista) {

            jcbCategoria.addItem(lista1.getNomeCategoria());

        }

    }

    /**
     * Método para calcular o preço do produto
     */
    public void calculaPreco() {

        if (!jtfPrecoCom.getText().trim().equals("") && !jtfImposto.getText().trim().equals("") && !jtfLucro.getText().trim().equals("")) {
            BigDecimal precoCom = new BigDecimal(jtfPrecoCom.getText().replaceAll("\\.", "").replace(",", ".").replace("R$ ", ""));

            BigDecimal lucro = new BigDecimal(jtfLucro.getText().replaceAll("\\.", "").replace(",", ".").replace("R$ ", ""));
            BigDecimal imposto = new BigDecimal(jtfImposto.getText().replaceAll("\\.", "").replace(",", ".").replace("R$ ", ""));

            BigDecimal vlimp = precoCom.multiply(imposto).divide(new BigDecimal(100));
            BigDecimal vllucro = precoCom.multiply(lucro).divide(new BigDecimal(100));
            BigDecimal vlvenda = precoCom.add(vllucro).add(vlimp);

            jtfPrecoVenda.setText(NumberFormat.getCurrencyInstance().format(vlvenda).replace("R$ ", ""));
        }
    }

    public void limparCampos() {
        jtfCodigo.setEditable(true);
        jtfCodigo.setText("");
        jtfDescricao.setText("");
        jcbUnidade.setSelectedIndex(0);
        jcbCategoria.setSelectedIndex(0);
        jtfPrecoCom.setText("");
        jtfLucro.setText("");
        jtfImposto.setText("");
        jtfPrecoVenda.setText("");
        jtfCodigo.grabFocus();
        jbtGravar.setVisible(true);
        jbtAlterar.setVisible(false);

    }

    public boolean validaCampos() {
        boolean retorno = false;
        if (jtfCodigo.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o Código do Produto!");
            jtfCodigo.grabFocus();
        } else if (jtfDescricao.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe a Descricão do Produto!");
            jtfDescricao.grabFocus();
        } else if (jcbUnidade.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Informe o Tipo de Unidade do Produto!");
            jcbUnidade.grabFocus();
        } else if (jcbCategoria.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Informe a Categoria do Produto!");
            jcbCategoria.grabFocus();
        } else if (jtfPrecoCom.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o Preço de Compra do Produto!");
            jtfPrecoCom.grabFocus();
        } else if (jtfLucro.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o Lucro!");
            jtfLucro.grabFocus();
        } else if (jtfImposto.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o Imposto!");
            jtfImposto.grabFocus();
        } else {
            retorno = true;
        }
        return retorno;

    }

}
