/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jarves.formularios;

import br.com.jarves.bancodedados.EstoqueDAO;
import br.com.jarves.bancodedados.ProdutoDAO;
import br.com.jarves.classes.Estoque;
import br.com.jarves.classes.Produtos;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;


/**
 *
 * @author Humberto
 */
public class jifEstoque extends javax.swing.JInternalFrame {

    int idEstoque;
    int idProduto;
    public jifEstoque() {
        initComponents();
        jbtAlterar.setVisible(false);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlbDescricão = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbCorredor = new javax.swing.JComboBox();
        jcbColuna = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jcbLinha = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jtfQuantidade = new javax.swing.JTextField();
        jbtInserir = new javax.swing.JButton();
        jbtAlterar = new javax.swing.JButton();
        jbtVoltar = new javax.swing.JButton();
        jtfProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbtVoltar1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setTitle("Registro de Categoria");
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Estoque"));
        jPanel2.setLayout(null);

        jlbDescricão.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jlbDescricão);
        jlbDescricão.setBounds(100, 20, 260, 30);

        jLabel2.setText("Corredor:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 170, 47, 14);

        jLabel3.setText("Coluna:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 210, 40, 20);

        jcbCorredor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbCorredor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "Y", "X", "Z" }));
        jPanel2.add(jcbCorredor);
        jcbCorredor.setBounds(100, 160, 110, 30);

        jcbColuna.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbColuna.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jPanel2.add(jcbColuna);
        jcbColuna.setBounds(100, 210, 110, 30);

        jLabel4.setText("Linha:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 260, 29, 14);

        jcbLinha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbLinha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jPanel2.add(jcbLinha);
        jcbLinha.setBounds(100, 260, 110, 30);

        jLabel5.setText("Quantidade:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 120, 60, 14);

        jtfQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfQuantidadeActionPerformed(evt);
            }
        });
        jPanel2.add(jtfQuantidade);
        jtfQuantidade.setBounds(100, 110, 50, 30);

        jbtInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jarves/icones/inserir.png.png"))); // NOI18N
        jbtInserir.setMnemonic('V');
        jbtInserir.setText("Inserir");
        jbtInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtInserirActionPerformed(evt);
            }
        });
        jbtInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtInserirKeyPressed(evt);
            }
        });
        jPanel2.add(jbtInserir);
        jbtInserir.setBounds(410, 30, 110, 40);

        jbtAlterar.setText("Alterar");
        jbtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtAlterar);
        jbtAlterar.setBounds(410, 80, 110, 40);

        jbtVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jarves/icones/voltar.png.jpg"))); // NOI18N
        jbtVoltar.setText("Sair");
        jbtVoltar.setActionCommand("");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtVoltar);
        jbtVoltar.setBounds(410, 190, 110, 40);

        jtfProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfProdutoKeyPressed(evt);
            }
        });
        jPanel2.add(jtfProduto);
        jtfProduto.setBounds(100, 60, 220, 30);

        jLabel6.setText("Produto:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 70, 50, 14);

        jbtVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jarves/icones/voltar.png.jpg"))); // NOI18N
        jbtVoltar1.setText("Cancelar");
        jbtVoltar1.setActionCommand("");
        jbtVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtVoltar1);
        jbtVoltar1.setBounds(410, 140, 110, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 550, 350);

        setBounds(0, 0, 575, 404);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtInserirActionPerformed

      
        
       
        if(validaDados()){
            Estoque estoque = new Estoque();
            EstoqueDAO ed = new EstoqueDAO();
            Produtos produtos = new Produtos();
            
            produtos.setIdProduto(idProduto);
            produtos.setDescricao(jtfProduto.getText());
            estoque.setCorEstoque(jcbCorredor.getSelectedItem().toString());
            estoque.setColEstoque(jcbColuna.getSelectedItem().toString());
            estoque.setLinEstoque(jcbLinha.getSelectedItem().toString());
            estoque.setQtdeEstoque(Integer.parseInt(jtfQuantidade.getText()));
            estoque.setProdutos(produtos);
            
            JOptionPane.showMessageDialog(null,ed.insereEstoque(estoque)); 
            jtfQuantidade.setText("");
            jcbColuna.setSelectedIndex(0);
            jcbCorredor.setSelectedIndex(0);
            jcbLinha.setSelectedIndex(0);
            jtfProduto.setText("");
            jlbDescricão.setText("");
            jtfProduto.grabFocus();
            
                
        }
    }//GEN-LAST:event_jbtInserirActionPerformed

    private void jbtInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtInserirKeyPressed

    }//GEN-LAST:event_jbtInserirKeyPressed

    private void jbtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAlterarActionPerformed
            if(validaDados()){
            Estoque estoque = new Estoque();
            EstoqueDAO ed = new EstoqueDAO();
            Produtos produtos = new Produtos();
            
            estoque.setIdEstoque(idEstoque);
            produtos.setDescricao(jtfProduto.getText().toLowerCase());
            estoque.setCorEstoque(jcbCorredor.getSelectedItem().toString());
            estoque.setColEstoque(jcbColuna.getSelectedItem().toString());
            estoque.setLinEstoque(jcbLinha.getSelectedItem().toString());
            estoque.setQtdeEstoque(Integer.parseInt(jtfQuantidade.getText()));
            estoque.setProdutos(produtos);
            
            
            JOptionPane.showMessageDialog(null, ed.alteraEstoque(estoque));
           
           
            jcbColuna.setSelectedIndex(0);
            jcbCorredor.setSelectedIndex(0);
            jcbLinha.setSelectedIndex(0);
            jtfProduto.setText("");
            jlbDescricão.setText("");
            jtfQuantidade.setText("");
            jbtAlterar.setVisible(false);
            jbtInserir.setVisible(true);
            jtfProduto.grabFocus();
            }

    }//GEN-LAST:event_jbtAlterarActionPerformed

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtVoltarActionPerformed

    private void jtfQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfQuantidadeActionPerformed

    private void jtfProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfProdutoKeyPressed
       if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
       
       Produtos produto = new Produtos();
       ProdutoDAO pdao = new ProdutoDAO();
       EstoqueDAO esdao = new EstoqueDAO();
       Estoque estoque;
       
       try{
           produto.setEanProduto(jtfProduto.getText().trim());
           estoque = esdao.getProdutos(produto);
           jlbDescricão.setText(estoque.getProdutos().getDescricao());
           jtfQuantidade.setText(""+estoque.getQtdeEstoque());
           jcbColuna.setSelectedItem(estoque.getColEstoque());
           jcbCorredor.setSelectedItem(estoque.getCorEstoque());
           jcbLinha.setSelectedItem(estoque.getLinEstoque());
           idProduto = estoque.getProdutos().getIdProduto();
           idEstoque = estoque.getIdEstoque();
           jbtAlterar.setVisible(true);
           jbtInserir.setVisible(false);
           jtfQuantidade.grabFocus();
       }catch(Exception ex){
          try{
          produto.setEanProduto(jtfProduto.getText().trim());
          pdao.getProdutos(produto);
          jlbDescricão.setText(produto.getDescricao());
          idProduto = produto.getIdProduto();
              
          if(produto.getDescricao().equals("")){
              JOptionPane.showMessageDialog(null, "Produto Não Localizado, Verifique o Registro de Produtos!");
              jtfProduto.setText("");
              jtfProduto.grabFocus();
          }else{
              jtfQuantidade.grabFocus();
          }
          
          }catch(NullPointerException e){
              JOptionPane.showMessageDialog(null, "Produto Não Localizado, Verifique o Registro de Produtos!");
          }
       }       
       
       
       idProduto = produto.getIdProduto();
       jlbDescricão.setText(produto.getDescricao());
       
       
       }
    }//GEN-LAST:event_jtfProdutoKeyPressed

    private void jbtVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltar1ActionPerformed
        jlbDescricão.setText("");
        jtfProduto.setText("");
        jtfQuantidade.setText("");
        jcbColuna.setSelectedIndex(0);
        jcbCorredor.setSelectedIndex(0);
        jcbLinha.setSelectedIndex(0);
        jbtAlterar.setVisible(false);
        jbtInserir.setVisible(true);
        jtfProduto.grabFocus();
    }//GEN-LAST:event_jbtVoltar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtAlterar;
    private javax.swing.JButton jbtInserir;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JButton jbtVoltar1;
    private javax.swing.JComboBox jcbColuna;
    private javax.swing.JComboBox jcbCorredor;
    private javax.swing.JComboBox jcbLinha;
    private javax.swing.JLabel jlbDescricão;
    private javax.swing.JTextField jtfProduto;
    private javax.swing.JTextField jtfQuantidade;
    // End of variables declaration//GEN-END:variables

    /**
     * Método para alinhar o internal frame no meio da tela
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, 0);
    }
    
   
        
        

    /**
     * Método para alimentar lista de categorias
     */
    

       public boolean validaDados(){
        
        boolean retorno = false;
        
        
        if(jtfProduto.getText() == null){
            JOptionPane.showMessageDialog(null, "Por Favor Informe o Código do Produto");
        }else if(jcbCorredor.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(null, "Por Favor Selecione Um corredor");
        }else if (jcbColuna.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Por Favor Selecione Uma Coluna");
        }else if(jcbLinha.getSelectedIndex() ==0){
            JOptionPane.showMessageDialog(null, "Por Favor Selecione Uma Linha");  
        }else if(jtfQuantidade.getText()== null){
            JOptionPane.showMessageDialog(null, "Por Favor Especifique a Quantidade");
        }else{
           retorno = true;
        } 
        return  retorno;

    }   
    
}
